apiVersion: v1
kind: Service
metadata:
  name: kourier
  namespace: kourier-system
  labels:
    networking.knative.dev/ingress-provider: kourier
    app.kubernetes.io/component: net-kourier
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/name: knative-serving
spec:
  ports:
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 31080  # Add this line
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
      nodePort: 31443  # Add this line
  selector:
    app: 3scale-kourier-gateway
  type: NodePort  # Change from LoadBalancer
